#
# This source code is released into the public domain.
#

TARGET	= netd
BINDIR	= sbin
SRCS	= netd.cc kq.cc netlink.cc iface.cc network.cc log.cc ctl.cc msgbus.cc
LIBS	= -lnv
MODULES	= isam nvl uuid

.include "../mk/prog.mk"
